# Driver Station
DRIVER_CONTROLLER_PORT = 0
TURN_TO_ZERO_BUTTON = 4
TURN_TO_NINETY_BUTTON = 3
TURN_TO_ONE_EIGHTY_BUTTON = 2
TURN_TO_NEGATIVE_NINETY_BUTTON = 1

# Drivetrain

# Ports
FRONT_RIGHT_MOTOR_PORT = 0
BACK_RIGHT_MOTOR_PORT = 1
FRONT_LEFT_MOTOR_PORT = 2
BACK_LEFT_MOTOR_PORT = 3

# Motor Speeds
DEFAULT_DRIVE_SPEED = 0.5
BOOST_DRIVE_SPEED = 1.0
DEFAULT_TURN_SPEED = 0.4
BOOST_TURN_SPEED = 0.7

# PID Constants (currently arbitrary)
TURN_P = 0.06
TURN_I = 0
TURN_D = 0

# Tolerances
TURN_TOLERANCE_DEGREES = 3

MAX_ACCELERATION = 0.7
