from math import pi


class DriveConstants:

    FRONT_RIGHT_MOTOR_PORT = 0
    BACK_RIGHT_MOTOR_PORT = 1
    FRONT_LEFT_MOTOR_PORT = 2
    BACK_LEFT_MOTOR_PORT = 3

    DEFAULT_LINEAR_SPEED = 0.5
    BOOST_LINEAR_SPEED = 1
    ANGULAR_SPEED = 0.5

    MAX_ACCELERATION_PER_SECOND = 1

    WHEELBASE_METRES = 21.8625 / 39.37

    S_VOLTS = 1
    V_VOLT_SECONDS_PER_METRE = 0.5
    A_VOLT_SECONDS_SQUARED_PER_METRE = 0

    P_GAIN = 1
    I_GAIN = 0
    D_GAIN = 0
    LINEAR_TOLERANCE_METRES = 0.12
    ANGULAR_TOLERANCE_DEGREES = 3

    # LEFT_ENCODER_PORT = 0
    # RIGHT_ENCODER_PORT = 1
    LEFT_ENCODER_PORTS = (0, 1)
    RIGHT_ENCODER_PORTS = (2, 3)

    ENCODER_CPR = 360
    WHEEL_DIAMETER_METRES = 0.1524
    ENCODER_DISTANCE_PER_PULSE = WHEEL_DIAMETER_METRES * pi / ENCODER_CPR

    IMU_PORT = 1


class DriverStationConstants:

    DRIVER_CONTROLLER_PORT = 0

    TURN_TO_ZERO_BUTTON = 4
    TURN_TO_NINETY_BUTTON = 3
    TURN_TO_ONE_EIGHTY_BUTTON = 2
    TURN_TO_NEGATIVE_NINETY_BUTTON = 1


class AutoConstants:
    pass
