# Driver Station
DRIVER_CONTROLLER_PORT = 0

# Drivetrain
FRONT_RIGHT_MOTOR_PORT = 0
BACK_RIGHT_MOTOR_PORT = 1
FRONT_LEFT_MOTOR_PORT = 2
BACK_LEFT_MOTOR_PORT = 3

# Motor Speeds
DEFAULT_DRIVE_SPEED = 0.7
BOOST_DRIVE_SPEED = 1.0
DEFAULT_TURN_SPEED = 0.4
BOOST_TURN_SPEED = 0.7

